version: '3'
services:
  mysql-server-1:
    image: mysql/mysql-server:8.0.12
    env_file:
      - mysql-server.env
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    networks:
        - gestbd_net

  mysql-server-2:
    image: mysql/mysql-server:8.0.12
    env_file:
      - mysql-server.env
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    networks:
        - gestbd_net

  mysql-server-3:
    image: mysql/mysql-server:8.0.12  
    env_file:
      - mysql-server.env
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]    
    networks:
        - gestbd_net

  mysql-shell:
    image: neumayer/mysql-shell-batch
    env_file:
      - mysql-shell.env
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-router
    networks:
        - gestbd_net

  mysql-router:
    image: mysql/mysql-router:8.0
    env_file:
      - mysql-router.env
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
    restart: on-failure
    networks:
        - gestbd_net

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    networks:
        - gestbd_net

networks:
    gestbd_net:
      driver: bridge
  